const team = [
{ name: 'Dasari Ishanvith', role: 'President', avatar: 'DI' },
{ name: 'P. Harini', role: 'Vice President', avatar: 'PH' },
{ name: 'Jeevan Reddy', role: 'Vice President', avatar: 'JR' },
{ name: 'Ridhima Balakrishna', role: 'General Secretary', avatar: 'RB' },
{ name: 'Ch Sai Harika', role: 'General Secretary', avatar: 'CSH' },
{ name: 'Ananth', role: 'General Secretary', avatar: 'AN' },
{ name: 'Sathvika Cheelamanthula', role: 'Joint Secretary', avatar: 'SC' },
{ name: 'Guduri Adhvika', role: 'Joint Secretary', avatar: 'GA' },
{ name: 'Manpreet Kaur', role: 'Treasurer', avatar: 'MK' },
{ name: 'M. Deekshitha', role: 'Treasurer', avatar: 'MD' },
{ name: 'Rohan Pudari', role: 'External Affairs', avatar: 'RP' },
{ name: 'Sadhika', role: 'Events Head', avatar: 'SA' },
{ name: 'Harsha', role: 'Events Head', avatar: 'HA' },
{ name: 'Abhinaya', role: 'Design Head', avatar: 'AB' },
{ name: 'Natalie Sasha', role: 'Design Head', avatar: 'NS' },
{ name: 'Manideep', role: 'Technical Head', avatar: 'MA' },
{ name: 'Manjunath', role: 'Technical Head', avatar: 'MJ' },
{ name: 'Ramya', role: 'Documentation Head', avatar: 'RA' },
{ name: 'Bhavya', role: 'Documentation Head', avatar: 'BH' },
{ name: 'Ruthwik', role: 'Sponsorship & Finance', avatar: 'RU' },
{ name: 'Vibhav', role: 'Sponsorship & Finance', avatar: 'VI' },
{ name: 'Faiz', role: 'PR Head', avatar: 'FA' },
{ name: 'Pranitha', role: 'PR Head', avatar: 'PR' },
{ name: 'Sathwik B S', role: 'Photography Head', avatar: 'SB' },
{ name: 'Shrithan', role: 'Photography Head', avatar: 'SH' },
{ name: 'Vikram', role: 'Logistics Head', avatar: 'VK' },
{ name: 'Ganesh', role: 'Logistics Head', avatar: 'GA' }
]


